import type {
  ArtifactSnapshot,
  MigrationCheckNoWriteCaseEvidence,
  MigrationCheckNoWriteEvidence,
} from "./model.js";

export function formatMigrationCheckNoWriteReport(
  evidence: MigrationCheckNoWriteEvidence,
): string {
  return [
    "# R3 EVD-3: Migration Check No-Write Failure Proof",
    "",
    `Evidence ID: \`${evidence.evidenceId}\``,
    `Validation checkpoint: \`${evidence.validationCheckpoint}\``,
    `Work package: \`${evidence.workPackage}\``,
    `Related issue: \`${evidence.issue}\``,
    "Generated by: `markdown-trace` local TypeScript migration-check evidence tests",
    "",
    "## Coverage Statement",
    "",
    "This proof covers the R3-3B no-write failure boundary for `markdown-trace migration-check`. Each probe runs the local command against a temporary repository copy, expects a non-zero exit, checks that generated artifact state is unchanged, and records the diagnostic signal that makes the failure actionable. The checked fixture bytes in the repository are not mutated.",
    "",
    "## Commands",
    "",
    "| Purpose | Command |",
    "| --- | --- |",
    "| Targeted R3 EVD-3 proof | `npm test -- tests/test_migration_check_no_write_evidence.test.ts` |",
    "| Focused migration check suite | `npm test -- tests/test_migration_check.test.ts tests/test_migration_check_no_write_evidence.test.ts` |",
    "| Full local regression suite | `npm test` |",
    "| TypeScript validation | `npm run typecheck` |",
    "| Build | `npm run build` |",
    "| R0 YAML compatibility baseline | `npm run validate:fixture` |",
    "| R0 derive compatibility baseline | `npm run derive:fixture` |",
    "| Passing migration command baseline | `npm run migration:check` |",
    "| Whitespace diff check | `git diff --check` |",
    "",
    "## Probe Results",
    "",
    "| Case | Command | Exit code | Artifact before | Artifact after | No-write proof | Diagnostic signal | Stderr | Status |",
    "| --- | --- | ---: | --- | --- | --- | --- | --- | --- |",
    ...evidence.cases.map(formatCaseRow),
    "",
    "## Review Boundary",
    "",
    "This evidence supports BEL-1237 / R3-3B only. It does not claim R3-3C YAML compatibility completion, full R2 fixture/profile matrix completion, operator policy readiness, YAML removal, generated sidecar authority, or source-authority flip approval.",
    "",
  ].join("\n");
}

function formatCaseRow(caseEvidence: MigrationCheckNoWriteCaseEvidence): string {
  return `| \`${caseEvidence.name}\` | \`${caseEvidence.command}\` | \`${caseEvidence.exitCode}\` | ${formatSnapshot(
    caseEvidence.artifactBefore,
  )} | ${formatSnapshot(caseEvidence.artifactAfter)} | ${escapeCell(
    caseEvidence.noWriteProof,
  )} | ${escapeCell(caseEvidence.diagnosticExcerpt)} | ${formatStderr(
    caseEvidence.stderr,
  )} | \`${caseEvidence.status}\` |`;
}

function formatSnapshot(snapshot: ArtifactSnapshot): string {
  if (snapshot.state === "missing") {
    return "`missing`";
  }

  return `\`present sha256=${snapshot.sha256 ?? "unknown"} size=${snapshot.sizeBytes ?? "unknown"}\``;
}

function formatStderr(stderr: string): string {
  return stderr === "" ? "none" : `\`${escapeCell(stderr)}\``;
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", "\\n");
}
