import type {
  ArtifactSnapshot,
  CommandProbeEvidence,
  MigrationCheckCompatibilityEvidence,
} from "./model.js";

export function formatMigrationCheckCompatibilityReport(
  evidence: MigrationCheckCompatibilityEvidence,
): string {
  return [
    "# R3 EVD-4/EVD-5: YAML Compatibility and Sidecar Byte-Stability Proof",
    "",
    `Evidence IDs: ${evidence.evidenceIds.map((id) => `\`${id}\``).join(", ")}`,
    `Validation checkpoints: ${evidence.validationCheckpoints
      .map((checkpoint) => `\`${checkpoint}\``)
      .join(", ")}`,
    `Work package: \`${evidence.workPackage}\``,
    `Related issue: \`${evidence.issue}\``,
    "Generated by: `markdown-trace` local TypeScript migration-check compatibility evidence tests",
    "",
    "## Coverage Statement",
    "",
    "This proof covers BEL-1238 / R3-3C only. It proves the existing R0 YAML `validate --registry` command path remains accepted and that the checked minimal R1 generated sidecar remains byte-stable under check mode after migration-check integration. The proof also records that the current migration-check path passes for the minimal R1 manual/generated pair.",
    "",
    "## Commands",
    "",
    "| Purpose | Command |",
    "| --- | --- |",
    "| Targeted R3 EVD-4/EVD-5 proof | `npm test -- tests/test_migration_check_compatibility.test.ts` |",
    "| Focused adjacent migration checks | `npm test -- tests/test_migration_check.test.ts tests/test_migration_check_no_write_evidence.test.ts tests/test_generated_sidecar.test.ts tests/test_valid_fixture_validation.test.ts` |",
    "| Full local regression suite | `npm test` |",
    "| TypeScript validation | `npm run typecheck` |",
    "| Build | `npm run build` |",
    "| R0 YAML compatibility baseline | `npm run validate:fixture` |",
    "| R0 derive compatibility baseline | `npm run derive:fixture` |",
    "| Passing migration command baseline | `npm run migration:check` |",
    "| Whitespace diff check | `git diff --check` |",
    "",
    "## R3-EVD-4: R0 YAML Compatibility",
    "",
    "| Probe | Claim | Command | Exit code | Signal | Stderr | Status |",
    "| --- | --- | --- | ---: | --- | --- | --- |",
    formatCommandRow(evidence.yamlCompatibility),
    "",
    "## R3-EVD-5: Generated Sidecar Byte Stability",
    "",
    "| Probe | Claim | Command | Exit code | Signal | Stderr | Status |",
    "| --- | --- | --- | ---: | --- | --- | --- |",
    formatCommandRow(evidence.migrationCheckCompatibility),
    formatCommandRow(evidence.sidecarByteStability),
    "",
    "## Byte Snapshot",
    "",
    "| Artifact | Before | After | Byte-stability proof | Bytes stable |",
    "| --- | --- | --- | --- | --- |",
    `| \`${evidence.sidecarByteStability.artifactPath}\` | ${formatSnapshot(
      evidence.sidecarByteStability.artifactBefore,
    )} | ${formatSnapshot(evidence.sidecarByteStability.artifactAfter)} | ${escapeCell(
      evidence.sidecarByteStability.byteStabilityProof,
    )} | \`${evidence.sidecarByteStability.bytesStable ? "YES" : "NO"}\` |`,
    "",
    "## Review Boundary",
    "",
    "This evidence supports BEL-1238 / R3-3C only. It does not claim full R2 fixture/profile matrix completion, negative matrix breadth, operator policy readiness, rollback rehearsal, CI enforcement, YAML removal, generated sidecar authority, or source-authority flip approval.",
    "",
  ].join("\n");
}

function formatCommandRow(evidence: CommandProbeEvidence): string {
  return `| \`${evidence.name}\` | ${escapeCell(evidence.claim)} | \`${evidence.command}\` | \`${evidence.exitCode}\` | ${formatSignal(
    evidence.stdoutSignal,
  )} | ${formatStderr(evidence.stderr)} | \`${evidence.status}\` |`;
}

function formatSnapshot(snapshot: ArtifactSnapshot): string {
  if (snapshot.state === "missing") {
    return "`missing`";
  }

  return `\`present sha256=${snapshot.sha256 ?? "unknown"} size=${snapshot.sizeBytes ?? "unknown"}\``;
}

function formatSignal(signal: string): string {
  return signal === "" ? "`<missing>`" : escapeCell(signal);
}

function formatStderr(stderr: string): string {
  return stderr === "" ? "none" : `\`${escapeCell(stderr)}\``;
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", "\\n");
}
