import { createHash } from "node:crypto";
import { cp, mkdir, mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";
import { parse } from "yaml";

import { main } from "../src/markdowntrace/cli.js";
import {
  buildGeneratedSidecarArtifact,
  generatedSidecarRelativePath,
  loadRegistry,
  writeGeneratedSidecarArtifact,
} from "../src/markdowntrace/registry/index.js";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const fixtureDirectory = "fixtures/r1-link-backed-entity-syntax";
const documentPath = `${fixtureDirectory}/minimal-link-backed-execution-spec.md`;
const typeProfilePath = `${fixtureDirectory}/minimal-type-profile.yaml`;
const sidecarPath = `${fixtureDirectory}/.markdown-trace/generated/minimal-link-backed-execution-spec--profile-minimal-type-profile-378211c9.entity-registry.yaml`;

interface ParsedGeneratedSidecar {
  readonly registryVersion: string;
  readonly document: {
    readonly path: string;
    readonly fixtureFamily: string;
  };
  readonly generated: {
    readonly artifactVersion: string;
    readonly artifactKind: string;
    readonly reviewMarker: string;
    readonly humanEditable: boolean;
    readonly source: {
      readonly documentPath: string;
      readonly documentSha256: string;
    };
    readonly typeProfile: {
      readonly path: string;
      readonly pathSha256: string;
      readonly contentSha256: string;
      readonly profileVersion: string;
    };
    readonly generator: {
      readonly packageName: string;
      readonly packageVersion: string;
      readonly command: string;
      readonly serialization: string;
    };
  };
  readonly entities: Array<{
    readonly id: string;
    readonly label: string;
    readonly type: string;
    readonly expectedReferences: {
      readonly labels: string[];
      readonly ranges: unknown[];
    };
  }>;
  readonly edges: Array<{
    readonly from: string;
    readonly relationship: string;
    readonly to: string;
  }>;
  readonly externalRefs: unknown[];
}

describe("generated sidecar artifacts", () => {
  it("derives the contract path from the source document and profile path", () => {
    expect(
      generatedSidecarRelativePath({
        documentRelativePath: documentPath,
        profileRelativePath: typeProfilePath,
      }),
    ).toBe(sidecarPath);
  });

  it("builds the checked minimal sidecar artifact with deterministic contract metadata", async () => {
    const result = await buildGeneratedSidecarArtifact({
      repoRoot,
      documentPath,
      typeProfilePath,
    });
    const checkedArtifact = await readFile(path.join(repoRoot, sidecarPath), "utf8");
    const parsed = parse(result.yaml) as ParsedGeneratedSidecar;

    expect(result.artifactRelativePath).toBe(sidecarPath);
    expect(result.yaml).toBe(checkedArtifact);
    expect(result.yaml.startsWith("# Generated by markdown-trace; do not edit by hand.\n")).toBe(
      true,
    );
    expect(result.yaml.endsWith("\n")).toBe(true);
    expect(parsed.registryVersion).toBe("markdown-trace.derived-registry.v0");
    expect(parsed.document).toMatchObject({
      path: documentPath,
      fixtureFamily: "r1-link-backed-entity-syntax",
    });
    expect(parsed.generated).toEqual({
      artifactVersion: "markdown-trace.generated-sidecar.v0",
      artifactKind: "registry",
      reviewMarker: "generated-by-markdown-trace",
      humanEditable: false,
      source: {
        documentPath,
        documentSha256: await sha256File(path.join(repoRoot, documentPath)),
      },
      typeProfile: {
        path: typeProfilePath,
        pathSha256: sha256Text(typeProfilePath),
        contentSha256: await sha256File(path.join(repoRoot, typeProfilePath)),
        profileVersion: "markdown-trace.type-profile.v1",
      },
      generator: {
        packageName: "markdown-trace",
        packageVersion: "0.1.0",
        command: `markdown-trace derive-sidecar --document ${documentPath} --type-profile ${typeProfilePath}`,
        serialization: "yaml-lf-final-newline-v0",
      },
    });
    expect(parsed.entities.map((entity) => [entity.id, entity.label, entity.type])).toEqual([
      ["exec.con.1", "CON-1", "constraint"],
      ["exec.wp.1", "WP-1", "work_package"],
    ]);
    expect(
      parsed.entities.find((entity) => entity.id === "exec.wp.1")?.expectedReferences,
    ).toEqual({
      labels: ["CON-1"],
      ranges: [],
    });
    expect(parsed.edges).toEqual([
      {
        from: "exec.wp.1",
        relationship: "references",
        to: "exec.con.1",
      },
    ]);
    expect(parsed.externalRefs).toEqual([]);
  });

  it("writes byte-stable sidecar output that existing registry loading accepts", async () => {
    const temporaryRepo = await preparedTemporaryRepo();

    try {
      const first = await writeGeneratedSidecarArtifact({
        repoRoot: temporaryRepo,
        documentPath,
        typeProfilePath,
      });
      const firstBytes = await readFile(first.artifactPath, "utf8");
      const second = await writeGeneratedSidecarArtifact({
        repoRoot: temporaryRepo,
        documentPath,
        typeProfilePath,
      });
      const registry = await loadRegistry(second.artifactPath);

      expect(second.artifactRelativePath).toBe(sidecarPath);
      expect(await readFile(second.artifactPath, "utf8")).toBe(firstBytes);
      expect(registry.document.path).toBe(documentPath);
      expect(registry.entities.map((entity) => entity.id)).toEqual([
        "exec.con.1",
        "exec.wp.1",
      ]);
    } finally {
      await rm(temporaryRepo, { recursive: true, force: true });
    }
  });

  it("exposes sidecar writing through the CLI", async () => {
    const temporaryRepo = await preparedTemporaryRepo();

    try {
      const stdout: string[] = [];
      const stderr: string[] = [];
      const exitCode = await main(
        ["derive-sidecar", "--document", documentPath, "--type-profile", typeProfilePath],
        {
          cwd: temporaryRepo,
          stdout: (text) => stdout.push(text),
          stderr: (text) => stderr.push(text),
        },
      );

      expect(exitCode).toBe(0);
      expect(stderr).toEqual([]);
      expect(stdout.join("")).toBe(`${sidecarPath}\n`);
      expect(await readFile(path.join(temporaryRepo, sidecarPath), "utf8")).toBe(
        await readFile(path.join(repoRoot, sidecarPath), "utf8"),
      );
    } finally {
      await rm(temporaryRepo, { recursive: true, force: true });
    }
  });
});

async function preparedTemporaryRepo(): Promise<string> {
  const temporaryRepo = await mkdtemp(path.join(os.tmpdir(), "markdown-trace-sidecar-"));

  for (const relativePath of ["package.json", documentPath, typeProfilePath]) {
    const targetPath = path.join(temporaryRepo, relativePath);

    await mkdir(path.dirname(targetPath), { recursive: true });
    await cp(path.join(repoRoot, relativePath), targetPath);
  }

  return temporaryRepo;
}

async function sha256File(filePath: string): Promise<string> {
  return sha256Buffer(await readFile(filePath));
}

function sha256Text(value: string): string {
  return sha256Buffer(Buffer.from(value));
}

function sha256Buffer(value: Buffer): string {
  return createHash("sha256").update(value).digest("hex");
}
