import type { CoverageMatrixEvidence, CoverageMatrixRow } from "./model.js";

export function formatCoverageMatrixReport(
  evidence: CoverageMatrixEvidence,
): string {
  return [
    "# R3 EVD-6: R2 Fixture/Profile Coverage Matrix",
    "",
    `Evidence ID: \`${evidence.evidenceId}\``,
    `Validation checkpoint: \`${evidence.validationCheckpoint}\``,
    `Work package: \`${evidence.workPackage}\``,
    `Related issue: \`${evidence.issue}\``,
    "Generated by: `markdown-trace` local TypeScript migration coverage matrix tests",
    "",
    "## Coverage Statement",
    "",
    "This matrix records the BEL-1239 / R3-4A fixture and profile coverage required by the R2 replacement criteria before any source-authority flip can be requested. Each row names the fixture inputs, command evidence, expected pass or fail behavior, observed evidence, and blocker state.",
    "",
    "## Commands",
    "",
    "| Purpose | Command |",
    "| --- | --- |",
    "| Targeted R3 EVD-6 proof | `npm test -- tests/test_migration_coverage_matrix.test.ts` |",
    "| Adjacent migration checks | `npm test -- tests/test_migration_check.test.ts tests/test_migration_check_no_write_evidence.test.ts tests/test_migration_check_compatibility.test.ts tests/test_type_profiles.test.ts` |",
    "| Full local regression suite | `npm test` |",
    "| TypeScript validation | `npm run typecheck` |",
    "| Build | `npm run build` |",
    "| R0 YAML compatibility baseline | `npm run validate:fixture` |",
    "| R0 derive compatibility baseline | `npm run derive:fixture` |",
    "| Passing migration command baseline | `npm run migration:check` |",
    "| Whitespace diff check | `git diff --check` |",
    "",
    "## Coverage Matrix",
    "",
    "| Case | Required coverage | Fixture inputs | Command evidence | Expected result | Expected behavior | Observed evidence | Blockers | Status |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ...evidence.rows.map(formatMatrixRow),
    "",
    "## Required Row Inventory",
    "",
    "| Field | Value |",
    "| --- | --- |",
    `| Missing required rows | ${formatMissingRows(evidence.missingRequiredCaseIds)} |`,
    `| Matrix status | \`${evidence.status}\` |`,
    "",
    "## Review Boundary",
    "",
    "This evidence supports BEL-1239 / R3-4A only. It does not claim R3-4B negative probe expansion, final policy documentation, rollback rehearsal, hosted CI enforcement, YAML removal, generated sidecar authority, replacement readiness, or source-authority flip approval.",
    "",
  ].join("\n");
}

function formatMatrixRow(row: CoverageMatrixRow): string {
  return `| \`${row.caseId}\`: ${escapeCell(row.caseName)} | ${escapeCell(
    row.requirement,
  )} | ${formatList(row.fixtureInputs)} | \`${escapeCell(row.command)}\` | \`${
    row.expectedResult
  }\` | ${escapeCell(row.expectedBehavior)} | ${escapeCell(
    row.observedEvidence,
  )} | ${formatList(row.blockers)} | \`${row.status}\` |`;
}

function formatMissingRows(missingRows: readonly string[]): string {
  return missingRows.length === 0 ? "`none`" : formatList(missingRows);
}

function formatList(values: readonly string[]): string {
  return values.length === 0
    ? "none"
    : values.map((value) => `\`${escapeCell(value)}\``).join("<br>");
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", "\\n");
}
