import type { DeterminismEvidence } from "../model.js";
import { displayDocumentPath, displayRegistryPath } from "../paths.js";

export function formatDeterminismReport(evidence: DeterminismEvidence): string {
  return [
    "# EVD-4: Deterministic Repeat Report",
    "",
    "Evidence ID: `EVD-4`",
    "Validation checkpoint: `VAL-5`",
    "Generated by: `markdown-trace` local TypeScript WP-4 evidence tests",
    "",
    "## Coverage Statement",
    "",
    "This repeat proof covers both selected MS-2 command paths: sidecar validation through `markdown-trace validate` and derived registry generation through `markdown-trace derive`. Each command was executed three times against the same fixture input, and the ordered stdout output was byte-identical for all three runs.",
    "",
    "## Inputs",
    "",
    "| Field | Value |",
    "| --- | --- |",
    `| Registry | \`${displayRegistryPath}\` |`,
    `| Document | \`${displayDocumentPath}\` |`,
    `| Markdown Engine package | \`${evidence.enginePackage}\` |`,
    `| Document contract version | \`${evidence.documentVersion}\` |`,
    "",
    "## Repeat Results",
    "",
    "| Command path | Command | Covered surface | Run exit codes | Ordered stdout hashes | Identical ordered output |",
    "| --- | --- | --- | --- | --- | --- |",
    ...evidence.commands.map(
      (commandEvidence) =>
        `| ${commandEvidence.pathName} | \`${commandEvidence.command}\` | ${commandEvidence.coverage} | ${commandEvidence.runs
          .map((run) => `\`${run.exitCode}\``)
          .join(", ")} | ${commandEvidence.outputHashes
          .map((hash) => `\`${hash}\``)
          .join("<br>")} | \`${commandEvidence.identicalOrderedOutputs ? "YES" : "NO"}\` |`,
    ),
    "",
  ].join("\n");
}
