import type { IssueKeyCollisionEvidence } from "../model.js";
import { displayDocumentPath, displayRegistryPath } from "../paths.js";

export function formatIssueKeyCollisionReport(
  evidence: IssueKeyCollisionEvidence,
): string {
  return [
    "# EVD-5: Issue-Key Collision Report",
    "",
    "Evidence ID: `EVD-5`",
    "Validation checkpoint: `VAL-5`",
    "Generated by: `markdown-trace` local TypeScript WP-4 evidence tests",
    "",
    "## Coverage Statement",
    "",
    `The fixture document contains the Linear-style issue key \`${evidence.issueKey}\` as source context. This proof confirms that \`${evidence.issueKey}\` remains outside the Markdown Trace document entity graph for both the sidecar registry graph and the derived registry graph.`,
    "",
    "## Inputs",
    "",
    "| Field | Value |",
    "| --- | --- |",
    `| Registry | \`${displayRegistryPath}\` |`,
    `| Document | \`${displayDocumentPath}\` |`,
    `| Registry version | \`${evidence.registryVersion}\` |`,
    `| Markdown Engine package | \`${evidence.enginePackage}\` |`,
    `| Document contract version | \`${evidence.documentVersion}\` |`,
    "",
    "## Collision Results",
    "",
    "| Surface | Issue key present in input | Entity IDs contain issue key | Entity labels contain issue key | Graph node IDs contain issue key | Graph node labels contain issue key | Graph edge endpoint IDs contain issue key | Graph edge endpoint labels contain issue key | External refs contain issue key | Status |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ...evidence.surfaces.map((surface) => formatSurfaceRow(evidence.issueKey, surface)),
    "",
  ].join("\n");
}

function formatSurfaceRow(
  issueKey: string,
  surface: IssueKeyCollisionEvidence["surfaces"][number],
): string {
  const entityIdCollision = containsIssueKey(surface.entityIds, issueKey);
  const entityCollision = containsIssueKey(surface.entityLabels, issueKey);
  const nodeIdCollision = containsIssueKey(surface.graphNodeIds, issueKey);
  const nodeCollision = containsIssueKey(surface.graphNodeLabels, issueKey);
  const edgeIdCollision = containsIssueKey(surface.graphEdgeEndpointIds, issueKey);
  const edgeCollision = containsIssueKey(surface.graphEdgeEndpointLabels, issueKey);
  const externalRefCollision =
    containsIssueKey(surface.externalReferenceKeys, issueKey) ||
    containsIssueKey(surface.externalReferenceRelatedEntities, issueKey);
  const status =
    surface.containsIssueKeyInInput &&
    !entityIdCollision &&
    !entityCollision &&
    !nodeIdCollision &&
    !nodeCollision &&
    !edgeIdCollision &&
    !edgeCollision &&
    !externalRefCollision
      ? "PASS"
      : "FAIL";

  return `| ${surface.surface} | \`${yesNo(surface.containsIssueKeyInInput)}\` | \`${yesNo(
    entityIdCollision,
  )}\` | \`${yesNo(
    entityCollision,
  )}\` | \`${yesNo(nodeIdCollision)}\` | \`${yesNo(nodeCollision)}\` | \`${yesNo(
    edgeIdCollision,
  )}\` | \`${yesNo(edgeCollision)}\` | \`${yesNo(
    externalRefCollision,
  )}\` | \`${status}\` |`;
}

function yesNo(value: boolean): string {
  return value ? "YES" : "NO";
}

function containsIssueKey(values: readonly string[], issueKey: string): boolean {
  return values.some((value) => value.includes(issueKey));
}
