import type { LocalSafetyEvidence } from "../model.js";
import { displayDocumentPath, displayRegistryPath } from "../paths.js";

export function formatLocalSafetyReport(evidence: LocalSafetyEvidence): string {
  return [
    "# EVD-6: Local Safety Report",
    "",
    "Evidence ID: `EVD-6`",
    "Validation checkpoint: `VAL-6`",
    "Generated by: `markdown-trace` local TypeScript WP-4 evidence tests",
    "",
    "## Coverage Statement",
    "",
    "This local-safety proof covers the selected MS-2 command paths: sidecar validation and derived registry generation. During in-process command execution, Node network entry points were guarded and recorded zero network attempts. Command writes were directed only to explicit operator-selected output paths under a temporary directory; the checked-in WP-4 evidence files under `docs/evidence/**` are the approved repository writes from this task.",
    "",
    "## Inputs",
    "",
    "| Field | Value |",
    "| --- | --- |",
    `| Registry | \`${displayRegistryPath}\` |`,
    `| Document | \`${displayDocumentPath}\` |`,
    `| Markdown Engine package | \`${evidence.enginePackage}\` |`,
    `| Document contract version | \`${evidence.documentVersion}\` |`,
    "",
    "## Safety Results",
    "",
    "| Command path | Command | Exit code | Network attempts | Live external-system mutation | Approved writes | Observed writes | Approved writes only | Repository status changed | Stderr | Status |",
    "| --- | --- | --- | ---: | --- | --- | --- | --- | --- | --- | --- |",
    ...evidence.commands.map(formatCommandRow),
    "",
  ].join("\n");
}

function formatCommandRow(commandEvidence: LocalSafetyEvidence["commands"][number]): string {
  const status =
    commandEvidence.exitCode === 0 &&
    commandEvidence.networkAttempts === 0 &&
    commandEvidence.approvedWritesOnly &&
    !commandEvidence.repositoryStatusChanged &&
    commandEvidence.stderr === ""
      ? "PASS"
      : "FAIL";

  return `| ${commandEvidence.pathName} | \`${commandEvidence.command}\` | \`${commandEvidence.exitCode}\` | ${commandEvidence.networkAttempts} | none | ${commandEvidence.approvedWrites
    .map((write) => `\`${write}\``)
    .join(", ")} | ${commandEvidence.observedWrites
    .map((write) => `\`${write}\``)
    .join(", ")} | \`${yesNo(commandEvidence.approvedWritesOnly)}\` | \`${yesNo(
    commandEvidence.repositoryStatusChanged,
  )}\` | ${commandEvidence.stderr === "" ? "none" : `\`${escapeCell(commandEvidence.stderr)}\``} | \`${status}\` |`;
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", "\\n");
}

function yesNo(value: boolean): string {
  return value ? "YES" : "NO";
}
