export {
  MIGRATION_COMPARISON_DIMENSIONS,
  MIGRATION_COMPARISON_SIDES,
  MIGRATION_DIMENSION_STATUSES,
  type MigrationComparisonDimension,
  type MigrationComparisonReport,
  type MigrationComparisonReportInput,
  type MigrationComparisonSide,
  type MigrationComparisonSideInput,
  type MigrationDelta,
  type MigrationDeltaValue,
  type MigrationDimensionResult,
  type MigrationDimensionSnapshot,
  type MigrationDimensionStatus,
  type MigrationGeneratedMetadata,
  type MigrationMissingValue,
  type MigrationNormalizationInput,
  type MigrationNormalizedComparison,
  type MigrationNormalizedDimension,
  type MigrationNormalizedEntry,
  type MigrationNormalizedValue,
  type MigrationValidationInput,
} from "./model.js";
export { compareMigrationPair } from "./compare.js";
export {
  normalizeGraphEntries,
  normalizeMetadataEntries,
  normalizeMigrationComparison,
  normalizeRegistryEntries,
  normalizeValidationEntries,
} from "./normalize.js";
