import type {
  BaselineRegressionCommandEvidence,
  BaselineRegressionEvidence,
} from "./model.js";
import { missingBaselineRegressionCommands } from "./model.js";

export function formatBaselineRegressionReport(
  evidence: BaselineRegressionEvidence,
): string {
  return [
    "# R3 EVD-9: Baseline Regression Suite Status",
    "",
    `Evidence ID: \`${evidence.evidenceId}\``,
    `Validation checkpoint: \`${evidence.validationCheckpoint}\``,
    `Work package: \`${evidence.workPackage}\``,
    `Related issue: \`${evidence.issue}\``,
    `Observed at: \`${evidence.observedAt}\``,
    "Generated by: `markdown-trace` local TypeScript baseline regression evidence tests",
    "",
    "## Baseline Statement",
    "",
    "This evidence records the BEL-1240 / R3-4B baseline regression commands required before MS-3 review. The command set preserves the existing TypeScript, test, build, R0 YAML compatibility, R0 derive compatibility, migration check, and whitespace-diff gates while the negative coverage evidence is expanded.",
    "",
    "## Command Status",
    "",
    "| Purpose | Command | Observed evidence | Status |",
    "| --- | --- | --- | --- |",
    ...evidence.commands.map(formatCommandRow),
    "",
    "## Required Command Inventory",
    "",
    "| Field | Value |",
    "| --- | --- |",
    `| Missing required commands | ${formatMissingCommands(
      missingBaselineRegressionCommands(evidence.commands),
    )} |`,
    `| Baseline status | \`${evidence.status}\` |`,
    "",
    "## Review Boundary",
    "",
    "This evidence supports BEL-1240 / R3-4B baseline regression status only. It does not claim final policy documentation, rollback rehearsal, hosted CI enforcement, YAML removal, generated sidecar authority, replacement readiness, or source-authority flip approval.",
    "",
  ].join("\n");
}

function formatCommandRow(row: BaselineRegressionCommandEvidence): string {
  return `| ${escapeCell(row.purpose)} | \`${escapeCell(
    row.command,
  )}\` | ${escapeCell(row.observedEvidence)} | \`${row.status}\` |`;
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", "\\n");
}

function formatMissingCommands(missingCommands: readonly string[]): string {
  return missingCommands.length === 0
    ? "`none`"
    : missingCommands.map((command) => `\`${escapeCell(command)}\``).join("<br>");
}
