import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { stringify } from "yaml";

import { loadTypeProfile } from "../profiles/loader.js";
import type { EntityTypeProfile } from "../profiles/model.js";
import { deriveRegistryResultFromMarkdown } from "./derived.js";
import { type SerializedRegistry, serializeRegistry } from "./serialization.js";

const GENERATED_SIDECAR_VERSION = "markdown-trace.generated-sidecar.v0";
const GENERATED_SIDECAR_KIND = "registry";
const GENERATED_REVIEW_MARKER = "generated-by-markdown-trace";
const GENERATED_SERIALIZATION = "yaml-lf-final-newline-v0";
const GENERATED_COMMENT = "# Generated by markdown-trace; do not edit by hand.";

interface GeneratedSidecarSourceMetadata {
  readonly documentPath: string;
  readonly documentSha256: string;
}

interface GeneratedSidecarTypeProfileMetadata {
  readonly path: string;
  readonly pathSha256: string;
  readonly contentSha256: string;
  readonly profileVersion: string;
}

interface GeneratedSidecarGeneratorMetadata {
  readonly packageName: string;
  readonly packageVersion: string;
  readonly command: string;
  readonly serialization: typeof GENERATED_SERIALIZATION;
}

interface GeneratedSidecarMetadata {
  readonly artifactVersion: typeof GENERATED_SIDECAR_VERSION;
  readonly artifactKind: typeof GENERATED_SIDECAR_KIND;
  readonly reviewMarker: typeof GENERATED_REVIEW_MARKER;
  readonly humanEditable: false;
  readonly source: GeneratedSidecarSourceMetadata;
  readonly typeProfile?: GeneratedSidecarTypeProfileMetadata;
  readonly generator: GeneratedSidecarGeneratorMetadata;
}

export interface GeneratedSidecarArtifact extends SerializedRegistry {
  readonly generated: GeneratedSidecarMetadata;
}

export interface BuildGeneratedSidecarOptions {
  readonly repoRoot: string;
  readonly documentPath: string;
  readonly typeProfilePath?: string;
}

export interface GeneratedSidecarResult {
  readonly artifact: GeneratedSidecarArtifact;
  readonly artifactPath: string;
  readonly artifactRelativePath: string;
  readonly yaml: string;
}

export async function buildGeneratedSidecarArtifact(
  options: BuildGeneratedSidecarOptions,
): Promise<GeneratedSidecarResult> {
  const repoRoot = path.resolve(options.repoRoot);
  const documentPath = path.resolve(repoRoot, options.documentPath);
  const documentRelativePath = repoRelativePath(repoRoot, documentPath, "document path");
  const documentBytes = await readFile(documentPath);
  const typeProfileContext = await loadTypeProfileContext(repoRoot, options.typeProfilePath);
  const { registry } = await deriveRegistryResultFromMarkdown(documentPath, {
    documentPath: documentRelativePath,
    ...(typeProfileContext === undefined
      ? {}
      : {
          typeProfile: typeProfileContext.profile,
          typeProfilePath: typeProfileContext.absolutePath,
        }),
  });
  const artifactRelativePath = generatedSidecarRelativePath({
    documentRelativePath,
    profileRelativePath: typeProfileContext?.relativePath,
  });
  const artifact = {
    ...serializeRegistry(registry),
    generated: {
      artifactVersion: GENERATED_SIDECAR_VERSION,
      artifactKind: GENERATED_SIDECAR_KIND,
      reviewMarker: GENERATED_REVIEW_MARKER,
      humanEditable: false,
      source: {
        documentPath: documentRelativePath,
        documentSha256: sha256Hex(documentBytes),
      },
      ...(typeProfileContext === undefined
        ? {}
        : {
            typeProfile: {
              path: typeProfileContext.relativePath,
              pathSha256: typeProfileContext.pathSha256,
              contentSha256: typeProfileContext.contentSha256,
              profileVersion: typeProfileContext.profile.profileVersion,
            },
          }),
      generator: {
        packageName: "markdown-trace",
        packageVersion: await packageVersion(repoRoot),
        command: generatedCommand(documentRelativePath, typeProfileContext?.relativePath),
        serialization: GENERATED_SERIALIZATION,
      },
    },
  } satisfies GeneratedSidecarArtifact;

  return {
    artifact,
    artifactPath: path.resolve(repoRoot, artifactRelativePath),
    artifactRelativePath,
    yaml: serializeGeneratedSidecar(artifact),
  };
}

export async function writeGeneratedSidecarArtifact(
  options: BuildGeneratedSidecarOptions,
): Promise<GeneratedSidecarResult> {
  const result = await buildGeneratedSidecarArtifact(options);

  await mkdir(path.dirname(result.artifactPath), { recursive: true });
  await writeFile(result.artifactPath, result.yaml, "utf8");

  return result;
}

export function generatedSidecarRelativePath(input: {
  readonly documentRelativePath: string;
  readonly profileRelativePath?: string;
}): string {
  if (!input.documentRelativePath.endsWith(".md")) {
    throw new Error("generated sidecar source document path must end in .md");
  }

  const sourceDirectory = path.posix.dirname(input.documentRelativePath);
  const sourceStem = path.posix.basename(input.documentRelativePath, ".md");
  const profileSegment =
    input.profileRelativePath === undefined
      ? ""
      : `--profile-${profileStem(input.profileRelativePath)}-${sha256Hex(input.profileRelativePath).slice(0, 8)}`;

  return path.posix.join(
    sourceDirectory === "." ? "" : sourceDirectory,
    ".markdown-trace",
    "generated",
    `${sourceStem}${profileSegment}.entity-registry.yaml`,
  );
}

export function serializeGeneratedSidecar(artifact: GeneratedSidecarArtifact): string {
  const yaml = stringify(
    {
      registryVersion: artifact.registryVersion,
      document: artifact.document,
      generated: artifact.generated,
      entities: artifact.entities,
      edges: artifact.edges,
      externalRefs: artifact.externalRefs,
    },
    { lineWidth: 0 },
  );

  return `${GENERATED_COMMENT}\n${yaml}`.trimEnd() + "\n";
}

interface TypeProfileContext {
  readonly absolutePath: string;
  readonly relativePath: string;
  readonly contentSha256: string;
  readonly pathSha256: string;
  readonly profile: EntityTypeProfile;
}

async function loadTypeProfileContext(
  repoRoot: string,
  typeProfilePath: string | undefined,
): Promise<TypeProfileContext | undefined> {
  if (typeProfilePath === undefined) {
    return undefined;
  }

  const absolutePath = path.resolve(repoRoot, typeProfilePath);
  const relativePath = repoRelativePath(repoRoot, absolutePath, "type profile path");
  const [profile, profileBytes] = await Promise.all([
    loadTypeProfile(absolutePath),
    readFile(absolutePath),
  ]);

  return {
    absolutePath,
    relativePath,
    contentSha256: sha256Hex(profileBytes),
    pathSha256: sha256Hex(relativePath),
    profile,
  };
}

async function packageVersion(repoRoot: string): Promise<string> {
  const packageData = JSON.parse(await readFile(path.join(repoRoot, "package.json"), "utf8")) as {
    version?: unknown;
  };

  if (typeof packageData.version !== "string" || packageData.version.trim() === "") {
    throw new Error("package.json version must be a non-empty string");
  }

  return packageData.version;
}

function generatedCommand(documentPath: string, typeProfilePath: string | undefined): string {
  return [
    "markdown-trace",
    "derive-sidecar",
    "--document",
    documentPath,
    ...(typeProfilePath === undefined ? [] : ["--type-profile", typeProfilePath]),
  ].join(" ");
}

function profileStem(profileRelativePath: string): string {
  const extension = profileRelativePath.endsWith(".yaml")
    ? ".yaml"
    : profileRelativePath.endsWith(".yml")
      ? ".yml"
      : path.posix.extname(profileRelativePath);

  return path.posix
    .basename(profileRelativePath, extension)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function repoRelativePath(repoRoot: string, targetPath: string, label: string): string {
  const relativePath = path.relative(repoRoot, targetPath);

  if (
    relativePath === "" ||
    relativePath.startsWith("..") ||
    path.isAbsolute(relativePath)
  ) {
    throw new Error(`${label} must be inside the repository root`);
  }

  return relativePath.split(path.sep).join("/");
}

function sha256Hex(value: string | Buffer): string {
  return createHash("sha256").update(value).digest("hex");
}
