import type { AnalysisLimits, DocumentAnalysis } from "./analysis.js";
import type { ContextBundle, ContextRequest } from "./context.js";
import type { TraceProfile } from "./profile.js";
import type { GraphSelection, LookupResult, ReferencePage, ReferenceQuery, TraversalQuery } from "./query.js";
import type { DocumentSource, Outcome } from "./source.js";
import type { ValidationReport } from "./validation.js";
export * from "./source.js";
export * from "./profile.js";
export * from "./analysis.js";
export * from "./validation.js";
export * from "./query.js";
export * from "./context.js";
export declare function compileProfile(input: unknown): Outcome<TraceProfile>;
export declare function analyzeDocument(source: DocumentSource, profile: TraceProfile, limits: AnalysisLimits): Outcome<DocumentAnalysis>;
export declare function validateGraph(analysis: DocumentAnalysis, profile: TraceProfile): Outcome<ValidationReport>;
export declare function lookupIdentifier(analysis: DocumentAnalysis, identifier: string): Outcome<LookupResult>;
export declare function findIncoming(analysis: DocumentAnalysis, identifier: string, query?: ReferenceQuery): Outcome<ReferencePage>;
export declare function findOutgoing(analysis: DocumentAnalysis, identifier: string, query?: ReferenceQuery): Outcome<ReferencePage>;
export declare function traverseGraph(analysis: DocumentAnalysis, query: TraversalQuery): Outcome<GraphSelection>;
export declare function extractContext(analysis: DocumentAnalysis, request: ContextRequest): Outcome<ContextBundle>;
