import type { NegativeEvidence } from "./model.js";
import { displayDocumentPath, displayRegistryPath } from "./paths.js";

export function formatNegativeEvidenceReport(evidence: NegativeEvidence): string {
  return [
    "# EVD-3: Negative Fixture Validation Report",
    "",
    "Evidence ID: `EVD-3`",
    "Validation checkpoint: `VAL-3`",
    "Generated by: `markdown-trace` local TypeScript validation tests",
    "",
    "## Coverage Statement",
    "",
    "The negative proof covers sidecar validation for missing registered definitions, missing references, missing edge targets, and incomplete bounded ranges. Duplicate canonical IDs and duplicate display labels are registry-load failures by design, because `EntityRegistry` construction rejects those inputs before validator findings can be produced. Derived registry generation is covered for the PR #14 bounded-range safety behavior: generated range expansion is bounded to registered labels while the sidecar validator remains responsible for reporting incomplete ranges against explicit sidecar expectations.",
    "",
    "## Commands",
    "",
    "| Purpose | Command |",
    "| --- | --- |",
    "| Targeted EVD-3 proof | `npm test -- tests/test_negative_fixture_evidence.test.ts` |",
    "| Full local regression suite | `npm test` |",
    "| TypeScript validation | `npm run typecheck` |",
    "| Derived-registry fixture check | `npm run derive:fixture` |",
    "| Valid sidecar fixture check | `npm run validate:fixture` |",
    "| Whitespace diff check | `git diff --check` |",
    "",
    "## Inputs",
    "",
    "| Field | Value |",
    "| --- | --- |",
    `| Registry | \`${displayRegistryPath}\` |`,
    `| Document | \`${displayDocumentPath}\` |`,
    `| Fixture family | \`${evidence.registry.document.fixtureFamily}\` |`,
    `| Registry version | \`${evidence.registry.registryVersion}\` |`,
    `| Markdown Engine package | \`${evidence.enginePackage}\` |`,
    `| Document contract version | \`${evidence.documentVersion}\` |`,
    "",
    "## Variant Results",
    "",
    "| Variant | Proof surface | Expected outcome | Actual outcome | Status |",
    "| --- | --- | --- | --- | --- |",
    ...evidence.outcomes.map(
      (outcome) =>
        `| \`${outcome.name}\` | ${outcome.proofSurface} | ${outcome.expectedOutcome} | ${outcome.actualOutcome} | \`${outcome.status}\` |`,
    ),
    "",
    "## Validator Findings",
    "",
    "| Variant | Category | Entity | Label | Relationship | Message |",
    "| --- | --- | --- | --- | --- | --- |",
    ...evidence.outcomes.flatMap((outcome) =>
      outcome.findings.map(
        (finding) =>
          `| \`${outcome.name}\` | \`${finding.category}\` | ${cell(
            finding.entityId,
          )} | ${cell(finding.label)} | ${cell(finding.edgeRelationship)} | ${escapeCell(
            finding.message,
          )} |`,
      ),
    ),
    "",
    "Registry-load failures are recorded in the variant results table because no validator result exists when duplicate canonical IDs or duplicate display labels fail during registry construction.",
    "",
  ].join("\n");
}

function cell(value: string | undefined): string {
  return value === undefined ? "" : `\`${escapeCell(value)}\``;
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|");
}
