/** Hand-authored expectations; no projection selector computes these values. */
const requiredSections = Object.freeze([
  Object.freeze({ id: '["scope","task","section"]', heading: "Scope", range: Object.freeze({ start: Object.freeze({ offset: 70, line: 5, column: 1 }), end: Object.freeze({ offset: 123, line: 9, column: 1 }) }), start: 70, end: 123, utf8Bytes: 53, text: "## Scope\n\nThe selected task has a narrow objective.\n\n", reason: "source-selection" }),
  Object.freeze({ id: '["authority","task","section"]', heading: "Authority", range: Object.freeze({ start: Object.freeze({ offset: 123, line: 9, column: 1 }), end: Object.freeze({ offset: 172, line: 13, column: 1 }) }), start: 123, end: 172, utf8Bytes: 49, text: "## Authority\n\nThe owner controls this contract.\n\n", reason: "source-selection" }),
  Object.freeze({ id: '["constraints","task","section"]', heading: "Constraints", range: Object.freeze({ start: Object.freeze({ offset: 172, line: 13, column: 1 }), end: Object.freeze({ offset: 222, line: 17, column: 1 }) }), start: 172, end: 222, utf8Bytes: 50, text: "## Constraints\n\nInputs are explicit and bounded.\n\n", reason: "source-selection" }),
  Object.freeze({ id: '["review","task","section"]', heading: "Review Boundary", range: Object.freeze({ start: Object.freeze({ offset: 222, line: 17, column: 1 }), end: Object.freeze({ offset: 281, line: 21, column: 1 }) }), start: 222, end: 281, utf8Bytes: 59, text: "## Review Boundary\n\nOnly declared criteria are evaluated.\n\n", reason: "source-selection" }),
]);
export const projectionOracle = Object.freeze({
  sourceAlias: "task",
  revision: "fixture-r1",
  roots: Object.freeze([{ source: "task", identifier: "WP-1" }]),
  capture: Object.freeze({
    identitySource: "analyzeDocument output only",
  }),
  requiredEntities: Object.freeze([
    Object.freeze({ source: "task", identifier: "WP-1" }),
    Object.freeze({ source: "task", identifier: "REQ-1" }),
    Object.freeze({ source: "task", identifier: "CON-1" }),
  ]),
  requiredSections,
  requiredSectionBytes: 211,
  sourceBytes: 697,
  requiredParts: Object.freeze([
    Object.freeze({ text: "# Task", start: 0, end: 6, utf8Bytes: 6, reasons: Object.freeze([
      Object.freeze({ obligationId: '["roots","task","WP-1"]', role: "heading" }),
      Object.freeze({ obligationId: '["scope","task","section"]', role: "heading" }),
      Object.freeze({ obligationId: '["authority","task","section"]', role: "heading" }),
      Object.freeze({ obligationId: '["constraints","task","section"]', role: "heading" }),
      Object.freeze({ obligationId: '["review","task","section"]', role: "heading" }),
      Object.freeze({ obligationId: '["acceptance","task","REQ-1"]', role: "heading" }),
      Object.freeze({ obligationId: '["dependencies","task","CON-1"]', role: "heading" }),
    ]) }),
    ...requiredSections.map(section => Object.freeze({
      text: section.text, start: section.start, end: section.end,
      utf8Bytes: section.utf8Bytes,
      reasons: Object.freeze([{ obligationId: section.id, role: "source-selection" }]),
    })),
    Object.freeze({ text: "## [Work](ctx://trace/entity/WP-1?role=definition)", start: 352, end: 402, utf8Bytes: 50, reasons: Object.freeze([{ obligationId: '["roots","task","WP-1"]', role: "owned-content" }]) }),
    Object.freeze({ text: "Implements [criterion](ctx://trace/entity/REQ-1?rel=implements).", start: 404, end: 468, utf8Bytes: 64, reasons: Object.freeze([{ obligationId: '["roots","task","WP-1"]', role: "owned-content" }]) }),
    Object.freeze({ text: "## [Criterion](ctx://trace/entity/REQ-1?role=definition)", start: 470, end: 526, utf8Bytes: 56, reasons: Object.freeze([{ obligationId: '["acceptance","task","REQ-1"]', role: "owned-content" }]) }),
    Object.freeze({ text: "Requires [constraint](ctx://trace/entity/CON-1?rel=requires).", start: 528, end: 589, utf8Bytes: 61, reasons: Object.freeze([{ obligationId: '["acceptance","task","REQ-1"]', role: "owned-content" }]) }),
    Object.freeze({ text: "## [Constraint](ctx://trace/entity/CON-1?role=definition)", start: 591, end: 648, utf8Bytes: 57, reasons: Object.freeze([{ obligationId: '["dependencies","task","CON-1"]', role: "owned-content" }]) }),
    Object.freeze({ text: "The bounded execution environment is required.", start: 650, end: 696, utf8Bytes: 46, reasons: Object.freeze([{ obligationId: '["dependencies","task","CON-1"]', role: "owned-content" }]) }),
  ]),
  requiredPartBytes: 551,
  requiredPartCount: 11,
  optionalSection: Object.freeze({ text: "## Optional Background\n\nThis source section is deliberately optional.\n\n", start: 281, end: 352, utf8Bytes: 71, reason: "optional" }),
  excludedText: "This source section is deliberately optional.",
  graphOnlyExcludedSections: Object.freeze(["Scope", "Authority", "Constraints", "Review Boundary"]),
  occurrenceIds: Object.freeze({ workDefinition: "O1", implementationReference: "O2", criterionDefinition: "O3", constraintReference: "O4", constraintDefinition: "O5", implementationRelationship: "R1", requirementRelationship: "R2" }),
  inclusionReasons: Object.freeze([
    Object.freeze({ obligationId: '["roots","task","WP-1"]', role: "owned-content" }),
    Object.freeze({ obligationId: '["scope","task","section"]', role: "source-selection" }),
    Object.freeze({ obligationId: '["authority","task","section"]', role: "source-selection" }),
    Object.freeze({ obligationId: '["constraints","task","section"]', role: "source-selection" }),
    Object.freeze({ obligationId: '["review","task","section"]', role: "source-selection" }),
    Object.freeze({ obligationId: '["acceptance","task","REQ-1"]', role: "owned-content" }),
    Object.freeze({ obligationId: '["dependencies","task","CON-1"]', role: "owned-content" }),
  ]),
  relationship: Object.freeze({
    from: Object.freeze({ source: "task", identifier: "WP-1" }),
    to: Object.freeze({ source: "task", identifier: "REQ-1" }),
    relation: "implements",
    originalReference: "[criterion](ctx://trace/entity/REQ-1?rel=implements)",
    depth: 1,
  }),
  evidenceCases: Object.freeze({
    incoming: Object.freeze([["REQ-2", "REQ-1", "o1", 1]]),
    both: Object.freeze([["REQ-1", "REQ-2", "o1", 1], ["REQ-2", "REQ-1", "o1", 2]]),
    repeated: Object.freeze([["REQ-1", "REQ-2", "o1", 1], ["REQ-1", "REQ-2", "o2", 1]]),
    cycle: Object.freeze([["REQ-1", "REQ-2", "o1", 1], ["REQ-2", "REQ-1", "o2", 2]]),
    selfLoop: Object.freeze([["REQ-1", "REQ-1", "o1", 1]]),
    unresolvedIncoming: Object.freeze([["REQ-2", null, "o3", 1]]),
    depthBoundary: Object.freeze([["REQ-1", "REQ-2", "o1", 1], ["REQ-2", "REQ-3", "o2", 2]]),
  }),
});
