import {
  MIGRATION_COMPARISON_DIMENSIONS,
  type MigrationComparisonDimension,
  type MigrationComparisonReport,
  type MigrationDelta,
  type MigrationDeltaValue,
  type MigrationDimensionResult,
  type MigrationDimensionStatus,
  type MigrationMissingValue,
} from "../migration/index.js";

const DIMENSION_ORDER = new Map<MigrationComparisonDimension, number>(
  MIGRATION_COMPARISON_DIMENSIONS.map((dimension, index) => [dimension, index]),
);

export function formatMigrationComparisonReport(report: MigrationComparisonReport): string {
  const dimensions = orderDimensionResults(report.dimensions);

  return [
    "# Migration Comparison Report",
    "",
    "Generated by: `markdown-trace` local TypeScript reporting harness",
    "",
    "## Inputs",
    "",
    "| Field | Value |",
    "| --- | --- |",
    `| Document | ${inlineCode(report.documentPath)} |`,
    `| Manual registry | ${inlineCode(report.manualRegistryPath)} |`,
    `| Generated sidecar | ${inlineCode(report.generatedSidecarPath)} |`,
    "",
    "## Result",
    "",
    "| Field | Value |",
    "| --- | ---: |",
    `| Exit code | ${inlineCode(report.exitCode)} |`,
    `| Equivalent dimensions | ${inlineCode(countDimensions(dimensions, "equivalent"))} |`,
    `| Intentional dimensions | ${inlineCode(countDimensions(dimensions, "intentional"))} |`,
    `| Blocking dimensions | ${inlineCode(countDimensions(dimensions, "blocking"))} |`,
    "",
    "## Dimensions",
    "",
    "| Dimension | Status | Deltas |",
    "| --- | --- | ---: |",
    ...dimensions.map(
      (dimension) =>
        `| ${inlineCode(dimension.dimension)} | ${inlineCode(dimension.status)} | ${inlineCode(
          dimension.deltas.length,
        )} |`,
    ),
    "",
    "## Delta Details",
    "",
    ...dimensions.flatMap(formatDimensionDetails),
    "",
  ].join("\n");
}

function formatDimensionDetails(dimension: MigrationDimensionResult): readonly string[] {
  const heading = `### ${titleCase(dimension.dimension)}`;
  const status = `Status: ${inlineCode(dimension.status)}`;

  if (dimension.deltas.length === 0) {
    return [heading, "", status, "", "No deltas.", ""];
  }

  return [
    heading,
    "",
    status,
    "",
    "| Status | Path | Expected | Actual | Rationale |",
    "| --- | --- | --- | --- | --- |",
    ...orderDeltas(dimension.deltas).map((delta) => formatDeltaRow(dimension.status, delta)),
    "",
  ];
}

function formatDeltaRow(status: MigrationDimensionStatus, delta: MigrationDelta): string {
  const cells = [
    inlineCode(status),
    inlineCode(delta.path),
    formatDeltaValue(delta.expected),
    formatDeltaValue(delta.actual),
    formatRationale(delta.rationale),
  ];

  return `| ${cells.join(" | ")} |`;
}

function countDimensions(
  dimensions: readonly MigrationDimensionResult[],
  status: MigrationDimensionStatus,
): number {
  return dimensions.filter((dimension) => dimension.status === status).length;
}

function orderDimensionResults(
  dimensions: readonly MigrationDimensionResult[],
): readonly MigrationDimensionResult[] {
  return [...dimensions].sort((left, right) => {
    const leftOrder = DIMENSION_ORDER.get(left.dimension) ?? Number.MAX_SAFE_INTEGER;
    const rightOrder = DIMENSION_ORDER.get(right.dimension) ?? Number.MAX_SAFE_INTEGER;

    return leftOrder === rightOrder
      ? compareTexts(left.dimension, right.dimension)
      : leftOrder - rightOrder;
  });
}

function orderDeltas(deltas: readonly MigrationDelta[]): readonly MigrationDelta[] {
  return [...deltas].sort((left, right) => compareTexts(left.path, right.path));
}

function formatDeltaValue(value: MigrationDeltaValue): string {
  return inlineCode(isMissingValue(value) ? "<missing>" : JSON.stringify(value));
}

function formatRationale(rationale: string): string {
  const trimmed = rationale.trim();
  return trimmed.length === 0 ? inlineCode("<none>") : escapeCell(trimmed);
}

function inlineCode(value: string | number | boolean): string {
  return `\`${escapeCell(String(value)).replaceAll("`", "&#96;")}\``;
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", "<br>");
}

function titleCase(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function compareTexts(left: string, right: string): number {
  if (left < right) {
    return -1;
  }

  if (left > right) {
    return 1;
  }

  return 0;
}

function isMissingValue(value: MigrationDeltaValue): value is MigrationMissingValue {
  return typeof value === "object" && value !== null && value.kind === "missing";
}
