import type { ValidationFinding } from "../validation/index.js";
import type { ValidationReportInput } from "./model.js";

export function formatValidationReport(input: ValidationReportInput): string {
  const { result } = input;
  const status = result.valid ? "PASS" : "FAIL";

  return [
    `# ${input.evidenceId}: Valid Fixture Validation Report`,
    "",
    `Evidence ID: \`${input.evidenceId}\``,
    `Validation checkpoint: \`${input.validationCheckpoint}\``,
    "Generated by: `markdown-trace` local TypeScript CLI/report harness",
    "",
    "## Inputs",
    "",
    "| Field | Value |",
    "| --- | --- |",
    `| Registry | \`${input.registryPath}\` |`,
    `| Document | \`${input.documentPath}\` |`,
    `| Fixture family | \`${input.registry.document.fixtureFamily}\` |`,
    `| Registry version | \`${input.registry.registryVersion}\` |`,
    "",
    "## Result",
    "",
    "| Field | Value |",
    "| --- | --- |",
    `| Exit code | \`${input.exitCode}\` |`,
    `| Status | \`${status}\` |`,
    `| Findings | \`${result.summary.findings}\` |`,
    `| Markdown Engine package | \`${result.metadata.enginePackage.name}@${result.metadata.enginePackage.version}\` |`,
    `| Document contract version | \`${result.metadata.documentVersion}\` |`,
    "",
    "## Summary",
    "",
    "| Metric | Count |",
    "| --- | ---: |",
    `| Registered entities | ${result.summary.entities} |`,
    `| Definitions resolved | ${result.summary.definitionsResolved} |`,
    `| Expected references resolved | ${result.summary.expectedReferencesResolved} |`,
    `| Expected ranges resolved | ${result.summary.expectedRangesResolved} |`,
    `| Edges resolved | ${result.summary.edgesResolved} |`,
    `| Findings | ${result.summary.findings} |`,
    "",
    "## Findings",
    "",
    formatFindings(result.findings),
    "",
  ].join("\n");
}

function formatFindings(findings: readonly ValidationFinding[]): string {
  if (findings.length === 0) {
    return "No findings.";
  }

  return [
    "| Category | Entity | Label | Relationship | Message |",
    "| --- | --- | --- | --- | --- |",
    ...findings.map(
      (finding) =>
        `| \`${finding.category}\` | ${cell(finding.entityId)} | ${cell(
          finding.label,
        )} | ${cell(finding.edgeRelationship)} | ${escapeCell(finding.message)} |`,
    ),
  ].join("\n");
}

function cell(value: string | undefined): string {
  return value === undefined ? "" : `\`${escapeCell(value)}\``;
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|");
}
